sched: Remove never used code in mm_cid_get()
stable inclusion
from stable-v6.6.115
commit 6d63703bec0c1fb3c68b47811f6d977183badf89
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8637

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=6d63703bec0c1fb3c68b47811f6d977183badf89

--------------------------------

[ Upstream commit 53abe3e1c154628cc74e33a1bfcd865656e433a5 ]

Clang is not happy with set but unused variable (this is visible
with `make W=1` build:

  kernel/sched/sched.h:3744:18: error: variable 'cpumask' set but not used [-Werror,-Wunused-but-set-variable]

It seems like the variable was never used along with the assignment
that does not have side effects as far as I can see.  Remove those
altogether.

Fixes: 223baf9d17f2 ("sched: Fix performance regression introduced by mm_cid")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Tested-by: Eric Biggers <ebiggers@kernel.org>
Reviewed-by: Breno Leitao <leitao@debian.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 6d63703bec0c1fb3c68b47811f6d977183badf89)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>