regulator: fixed: Rely on the core freeing the enable GPIO
mainline inclusion
from mainline-v6.19-rc1
commit 79a45ddcdbba330f5139c7c7ff7042d69cf147b2
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8763

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=79a45ddcdbba330f5139c7c7ff7042d69cf147b2

--------------------------------

In order to simplify ownership rules for enable GPIOs supplied by drivers
regulator_register() always takes ownership of them, even if it ends up
failing for some other reason. We therefore should not free the GPIO if
registration fails but just let the core worry about things.

Fixes: 636f4618b1cd (regulator: fixed: fix GPIO descriptor leak on register failure)
Reported-by: Diederik de Haas <diederik@cknow-tech.com>
Closes: https://lore.kernel.org/r/DEPEYUF5BRGY.UKFBWRRE8HNP@cknow-tech.com
Tested-by: Diederik de Haas <diederik@cknow-tech.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
Link: https://patch.msgid.link/20251204-regulator-fixed-fix-gpiod-leak-v1-1-48efea5b82c2@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>
[Fix drivers/regulator/fixed.c:182:6: error: unused variable ‘ret’ [-Werror=unused-variable]
  182 |  int ret;
      |      ^~~]
(cherry picked from commit 79a45ddcdbba330f5139c7c7ff7042d69cf147b2)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>