LoongArch: Eliminate superfluous get_numa_distances_cnt()
stable inclusion
from stable-v6.6.88
commit 37491e1dbb50fa3d37c0a4e33965d053ed47da0c
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ID6MDL

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=37491e1dbb50fa3d37c0a4e33965d053ed47da0c

--------------------------------

commit a0d3c8bcb9206ac207c7ad3182027c6b0a1319bb upstream.

In LoongArch, get_numa_distances_cnt() isn't in use, resulting in a
compiler warning.

Fix follow errors with clang-18 when W=1e:

arch/loongarch/kernel/acpi.c:259:28: error: unused function 'get_numa_distances_cnt' [-Werror,-Wunused-function]
  259 | static inline unsigned int get_numa_distances_cnt(struct acpi_table_slit *slit)
      |                            ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Link: https://lore.kernel.org/all/Z7bHPVUH4lAezk0E@kernel.org/
Signed-off-by: Yuli Wang <wangyuli@uniontech.com>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 37491e1dbb50fa3d37c0a4e33965d053ed47da0c)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>