md: dm-zoned-target: Initialize return variable r to avoid uninitialized use
stable inclusion
from stable-v6.6.103
commit d386c8e4e587c910b97caee9bd25732729bd7ed3
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8365

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=d386c8e4e587c910b97caee9bd25732729bd7ed3

--------------------------------

[ Upstream commit 487767bff572d46f7c37ad846c4078f6d6c9cc55 ]

Fix Smatch-detected error:
drivers/md/dm-zoned-target.c:1073 dmz_iterate_devices()
error: uninitialized symbol 'r'.

Smatch detects a possible use of the uninitialized variable 'r' in
dmz_iterate_devices() because if dmz->nr_ddevs is zero, the loop is
skipped and 'r' is returned without being set, leading to undefined
behavior.

Initialize 'r' to 0 before the loop. This ensures that if there are no
devices to iterate over, the function still returns a defined value.

Signed-off-by: Purva Yeshi <purvayeshi550@gmail.com>
Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit d386c8e4e587c910b97caee9bd25732729bd7ed3)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>