hrtimers: Mark is_migration_base() with __always_inline
stable inclusion
from stable-v6.6.84
commit a625ad9b5b1b9272b5bcda3190dcbd184a38c639
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ICCVOJ

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=a625ad9b5b1b9272b5bcda3190dcbd184a38c639

--------------------------------

[ Upstream commit 27af31e44949fa85550176520ef7086a0d00fd7b ]

When is_migration_base() is unused, it prevents kernel builds
with clang, `make W=1` and CONFIG_WERROR=y:

kernel/time/hrtimer.c:156:20: error: unused function 'is_migration_base' [-Werror,-Wunused-function]
  156 | static inline bool is_migration_base(struct hrtimer_clock_base *base)
      |                    ^~~~~~~~~~~~~~~~~

Fix this by marking it with __always_inline.

[ tglx: Use __always_inline instead of __maybe_unused and move it into the
  	usage sites conditional ]

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Link: https://lore.kernel.org/all/20250116160745.243358-1-andriy.shevchenko@linux.intel.com
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit a625ad9b5b1b9272b5bcda3190dcbd184a38c639)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>