net: xgene-v2: remove incorrect ACPI_PTR annotation
stable inclusion
from stable-v6.6.93
commit 7819a7dcf0412612782bbb12f7544b754b4c8c7e
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8365

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=7819a7dcf0412612782bbb12f7544b754b4c8c7e

--------------------------------

[ Upstream commit 01358e8fe922f716c05d7864ac2213b2440026e7 ]

Building with W=1 shows a warning about xge_acpi_match being unused when
CONFIG_ACPI is disabled:

drivers/net/ethernet/apm/xgene-v2/main.c:723:36: error: unused variable 'xge_acpi_match' [-Werror,-Wunused-const-variable]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250225163341.4168238-2-arnd@kernel.org
Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 7819a7dcf0412612782bbb12f7544b754b4c8c7e)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>