platform/x86/intel/pmt: fix build dependency for kunit test
mainline inclusion
from mainline-v6.17-rc1
commit 5a9fffd8a533bfb2688ec69dd6d1b6e53ef1177a
category: feature
bugzilla: https://atomgit.com/openeuler/intel-kernel/issues/186
CVE: NA
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5a9fffd8a533bfb2688ec69dd6d1b6e53ef1177a

-------------------------------------------------

Intel-SIG: commit 5a9fffd8a533 platform/x86/intel/pmt: fix build dependency for kunit test
Backport PMT spec 3.0 support (Discovery driver and preparation for PMT AET)

When INTEL_PMT_TELEMETRY is in a loadable module, the discovery
test cannot be built-in:

x86_64-linux-ld: drivers/platform/x86/intel/pmt/discovery-kunit.o: in function `test_intel_pmt_get_regions_by_feature':
discovery-kunit.c:(.text+0x29d): undefined reference to `intel_pmt_get_regions_by_feature'
x86_64-linux-ld: discovery-kunit.c:(.text+0x2c3): undefined reference to `intel_pmt_put_feature_group'

Add a Kconfig dependency to prevent this.

Fixes: b9707d46a959 ("platform/x86/intel/pmt: KUNIT test for PMT Enhanced Discovery API")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20250714081559.4056777-1-arnd@kernel.org
Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
[ Zhang Rui: amend commit log ]
Signed-off-by: Zhang Rui <rui.zhang@intel.com>