bpftool: Fix -Wuninitialized-const-pointer warnings with clang >= 21
stable inclusion
from stable-v6.6.117
commit 4b78d57b7dd375f38b4f0be79a00530ba4ff5a11
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8763

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=4b78d57b7dd375f38b4f0be79a00530ba4ff5a11

--------------------------------

[ Upstream commit 5612ea8b554375d45c14cbb0f8ea93ec5d172891 ]

This fixes the build with -Werror -Wall.

btf_dumper.c:71:31: error: variable 'finfo' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
   71 |         info.func_info = ptr_to_u64(&finfo);
      |                                      ^~~~~

prog.c:2294:31: error: variable 'func_info' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 2294 |         info.func_info = ptr_to_u64(&func_info);
      |

v2:
  - Initialize instead of using memset.

Signed-off-by: Tom Stellard <tstellar@redhat.com>
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Acked-by: Quentin Monnet <qmo@kernel.org>
Link: https://lore.kernel.org/bpf/20250917183847.318163-1-tstellar@redhat.com
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 4b78d57b7dd375f38b4f0be79a00530ba4ff5a11)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>