gfs2: Set .migrate_folio in gfs2_{rgrp,meta}_aops
stable inclusion
from stable-v6.6.103
commit 3d2c05cbc6a3725d832b912b637971f37301c7e5
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8365

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=3d2c05cbc6a3725d832b912b637971f37301c7e5

--------------------------------

[ Upstream commit 5c8f12cf1e64e0e8e6cb80b0c935389973e8be8d ]

Clears up the warning added in 7ee3647243e5 ("migrate: Remove call to
->writepage") that occurs in various xfstests, causing "something found
in dmesg" failures.

[  341.136573] gfs2_meta_aops does not implement migrate_folio
[  341.136953] WARNING: CPU: 1 PID: 36 at mm/migrate.c:944 move_to_new_folio+0x2f8/0x300

Signed-off-by: Andrew Price <anprice@redhat.com>
Signed-off-by: Andreas Gruenbacher <agruenba@redhat.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 3d2c05cbc6a3725d832b912b637971f37301c7e5)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>