xsched: fix compile error when CONFIG_XCU_SCHEDULER is disabled
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ID9IFI

-----------------------------------------

If CONFIG_XCU_SCHEDULER is not enabled, these two system calls
sys_xsched_getattr and sys_xsched_setattr will not be defined, causing
compilation errors.

ld: vmlinux.o: in function `x64_sys_call':
(.text+0x169b): undefined reference to `__x64_sys_xsched_getattr'
ld: (.text+0x29f8): undefined reference to `__x64_sys_xsched_setattr'
ld: vmlinux.o:(.rodata+0x1078): undefined reference to
`__x64_sys_xsched_setattr'
ld: vmlinux.o:(.rodata+0x1080): undefined reference to
`__x64_sys_xsched_getattr'
make[2]: *** [scripts/Makefile.vmlinux:37: vmlinux] Error 1

Therefore, it is necessary to add stub functions for these two system
calls to avoid errors.

Fixes: 832cfa264d7c ("xsched: add xsched_{set,get}attr syscall")
Signed-off-by: Liu Kai <liukai284@huawei.com>