MIPS: cm: Fix warning if MIPS_CM is disabled
stable inclusion
from stable-v6.6.89
commit 17d41d0f3a2683be946a0e2d134660481a250029
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ID73WA

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=17d41d0f3a2683be946a0e2d134660481a250029

--------------------------------

commit b73c3ccdca95c237750c981054997c71d33e09d7 upstream.

Commit e27fbe16af5c ("MIPS: cm: Detect CM quirks from device tree")
introduced

arch/mips/include/asm/mips-cm.h:119:13: error: ‘mips_cm_update_property’
	defined but not used [-Werror=unused-function]

Fix this by making empty function implementation inline

Fixes: e27fbe16af5c ("MIPS: cm: Detect CM quirks from device tree")
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 17d41d0f3a2683be946a0e2d134660481a250029)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>