platform/x86/intel/pmt/discovery: fix format string warning
mainline inclusion
from mainline-v6.17-rc1
commit 6382c27389c266e90b31151a79d81fa6e122d2d6
category: feature
bugzilla: https://atomgit.com/openeuler/intel-kernel/issues/186
CVE: NA
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6382c27389c266e90b31151a79d81fa6e122d2d6

-------------------------------------------------

Intel-SIG: commit 6382c27389c2 platform/x86/intel/pmt/discovery: fix format string warning
Backport PMT spec 3.0 support (Discovery driver and preparation for PMT AET)

When -Wformat-security is enabled, this new code triggers it:

drivers/platform/x86/intel/pmt/discovery.c: In function 'pmt_features_discovery':
drivers/platform/x86/intel/pmt/discovery.c:505:36: error: format not a string literal and no format arguments [-Werror=format-security]
  505 |                                    pmt_feature_names[feature->id]);

Fixes: d9a078809356 ("platform/x86/intel/pmt: Add PMT Discovery driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20250711072718.2748415-1-arnd@kernel.org
Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
[ Zhang Rui: amend commit log ]
Signed-off-by: Zhang Rui <rui.zhang@intel.com>