scsi: ufs: host: mediatek: Require CONFIG_PM
mainline inclusion
from mainline-v7.0-rc1
commit bbb8d98fb4536594cb104fd630ea0f7dce3771d6
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8763

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=bbb8d98fb4536594cb104fd630ea0f7dce3771d6

--------------------------------

The added print statement from a recent fix causes the driver to fail
building when CONFIG_PM is disabled:

drivers/ufs/host/ufs-mediatek.c: In function 'ufs_mtk_resume':
drivers/ufs/host/ufs-mediatek.c:1890:40: error: 'struct dev_pm_info' has no member named 'request'
 1890 |                         hba->dev->power.request,

It seems unlikely that the driver can work at all without CONFIG_PM, so
just add a dependency and remove the existing ifdef checks, rather than
adding another ifdef.

Fixes: 15ef3f5aa822 ("scsi: ufs: host: mediatek: Enhance recovery on resume failure")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@collabora.com>
Link: https://patch.msgid.link/20260202095052.1232703-1-arnd@kernel.org
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit bbb8d98fb4536594cb104fd630ea0f7dce3771d6)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>