platform/x86/intel-uncore-freq: avoid non-literal format string
mainline inclusion
from mainline-v6.16-rc3
commit 0c44b46f51a17baa7ab67de1464427116e9c4eaa
category: feature
bugzilla: https://gitee.com/openeuler/intel-kernel/issues/ID58QM
CVE: NA
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0c44b46f51a17baa7ab67de1464427116e9c4eaa

-------------------------------------------------

Intel-SIG: commit 0c44b46f51a1 platform/x86/intel-uncore-freq: avoid non-literal format string
Backport uncore freq driver fixes and support for agent_types and die_id sysfs attributes

Using a string variable in place of a format string causes a W=1 build warning:

drivers/platform/x86/intel/uncore-frequency/uncore-frequency-common.c:61:40: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
   61 |                 length += sysfs_emit_at(buf, length, agent_name[agent]);
      |                                                      ^~~~~~~~~~~~~~~~~

Use the safer "%s" format string to print it instead.

Fixes: b98fa870fce2 ("platform/x86/intel-uncore-freq: Add attributes to show agent types")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Tested-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
Link: https://lore.kernel.org/r/20250610093459.2646337-1-arnd@kernel.org
Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
[ Zhang Rui: amend commit log ]
Signed-off-by: Zhang Rui <rui.zhang@intel.com>