arm64: fix compile error if CONFIG_ARCH_HAS_COPY_MC not enabled
hulk inclusion
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8386

------------------------------------------

If CONFIG_ARCH_HAS_COPY_MC is not enabled, kernel can not be compiled
with the following error:
  aarch64-linux-gnu-ld: arch/arm64/mm/flush.o: in function `copy_mc_to_user_page':
  arch/arm64/mm/flush.c:56:(.text+0x3a4): undefined reference to `memcpy_mc'
  aarch64-linux-gnu-ld: mm/memory.o: in function `__access_remote_vm':
  mm/memory.c:6674:(.text+0xe138): undefined reference to `memcpy_mc'

  aarch64-linux-gnu-ld: mm/kasan/shadow.o: in function `memcpy_mc':
  mm/kasan/shadow.c:90:(.text+0xa94): undefined reference to `__memcpy_mc'

Fix this by add stub function of memcpy_mc which just call memcpy.

Fixes: d51d1b114c86 ("arm64: mm: support recovery from copy_{from/to}_user_page()")
Fixes: b991780c836c ("arm64: introduce copy_mc_to_kernel() implementation")
Signed-off-by: Wupeng Ma <mawupeng1@huawei.com>