apparmor: use the condition in AA_BUG_FMT even with debug disabled
stable inclusion
from stable-v6.6.103
commit f8c001884bb4da56ce5617ed6c747ae61a17878f
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8365

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=f8c001884bb4da56ce5617ed6c747ae61a17878f

--------------------------------

[ Upstream commit 67e370aa7f968f6a4f3573ed61a77b36d1b26475 ]

This follows the established practice and fixes a build failure for me:
security/apparmor/file.c: In function ‘__file_sock_perm’:
security/apparmor/file.c:544:24: error: unused variable ‘sock’ [-Werror=unused-variable]
  544 |         struct socket *sock = (struct socket *) file->private_data;
      |                        ^~~~

Signed-off-by: Mateusz Guzik <mjguzik@gmail.com>
Signed-off-by: John Johansen <john.johansen@canonical.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit f8c001884bb4da56ce5617ed6c747ae61a17878f)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>