Linkdata：net：fix sxe compile errors 'sxe_resume' defined but not used
linkdata inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IC8V2K
CVE: NA

--------------------------------

when compile sxe without CONFIG_PM_SLEEP, it is failed:
make bcm2711_defconfig
make -j$(nproc)

CC [M]  drivers/net/wireless/ath/ath9k/htc_drv_txrx.o
drivers/net/ethernet/linkdata/sxe/sxepf/sxe_main.c:1071:12: error:
'sxe_resume' defined but not used [-Werror=unused-function]
 1071 | static int sxe_resume(struct device *dev)
      |            ^~~~~~~~~~
drivers/net/ethernet/linkdata/sxe/sxepf/sxe_main.c:1038:12: error:
'sxe_suspend' defined but not used [-Werror=unused-function]
 1038 | static int sxe_suspend(struct device *dev)
      |            ^~~~~~~~~~~
  CC [M]  drivers/net/ethernet/intel/i40e/i40e_common.o
cc1: all warnings being treated as errors

Fixes: dd013ad48753 ("Ethernet: Linkdata: Supports Linkdata ethernet Controllers")
Signed-off-by: liujie_answer <liujie5@linkdatatechnology.com>