drm/bridge: it6505: select REGMAP_I2C
stable inclusion
from stable-v6.6.112
commit d2e29c36eb5f9557ec402a06b84f44ac9b490d54
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8637

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=d2e29c36eb5f9557ec402a06b84f44ac9b490d54

--------------------------------

[ Upstream commit 21b137f651cf9d981e22d2c60a2a8105f50a6361 ]

Fix

  aarch64-linux-gnu-ld: drivers/gpu/drm/bridge/ite-it6505.o: in function `it6505_i2c_probe':
  ite-it6505.c:(.text+0x754): undefined reference to `__devm_regmap_init_i2c'

Signed-off-by: Chia-I Wu <olvaffe@gmail.com>
Fixes: b5c84a9edcd4 ("drm/bridge: add it6505 driver")
Reviewed-by: Chen-Yu Tsai <wenst@chromium.org>
Link: https://patch.msgid.link/20250610235825.3113075-1-olvaffe@gmail.com
Signed-off-by: Chen-Yu Tsai <wenst@chromium.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit d2e29c36eb5f9557ec402a06b84f44ac9b490d54)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>