vdpa:Adding compilation macro to decouple the vdpa and iommufd modules
virt inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IC9INY
CVE: NA

---------------------------------------------------------

Adding compilation macro to decouple the vdpa and iommufd modules.
Fixes the following error:
```
   drivers/vhost/vdpa.c: In function 'vhost_vdpa_bind_iommufd':
>> drivers/vhost/vdpa.c:589:23: error: implicit declaration of function
>> 'iommufd_ctx_from_fd'; did you mean 'iommufd_ctx_from_file'?
>> [-Werror=implicit-function-declaration]
     589 |         iommufd_ctx = iommufd_ctx_from_fd(bind.iommufd);
         |                       ^~~~~~~~~~~~~~~~~~~
         |                       iommufd_ctx_from_file
>> drivers/vhost/vdpa.c:589:21: warning: assignment to 'struct
>> iommufd_ctx *' from 'int' makes pointer from integer without a cast
>> [-Wint-conversion]
     589 |         iommufd_ctx = iommufd_ctx_from_fd(bind.iommufd);
         |                     ^
   cc1: some warnings being treated as errors
```

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202505070025.y1C68ZCV-lkp@intel.com
Fixes: 6a58b8be556f ("vhost/vdpa: Add support to bind and attach iommufd")
Signed-off-by: libai <libai12@huawei.com>