RNPVF: NET: Fix rnpvf compile errors without CONFIG_MXGBEVF_FIX_VF_QUEUE
mucse inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IB08ZJ
CVE: NA

--------------------------------

when compile rnpvf withou CONFIG_MXGBEVF_FIX_VF_QUEUE, it is failed:
../drivers/net/ethernet/mucse/rnpvf/rnpvf_main.c:5583:32: error: called object
type 'int' is not a function or function pointer
 5583 |                 v = rd32(hw, RNP_DMA_RX_START(ring));
         |                              ~~~~~~~~~~~~~~~~^
../drivers/net/ethernet/mucse/rnpvf/rnpvf_regs.h:116:53: note: expanded
from macro 'rd32'
  116 | #define rd32(hw, off) rnpvf_rd_reg((hw)->hw_addr + (off))
        |                                                     ^~~
../drivers/net/ethernet/mucse/rnpvf/rnpvf_regs.h:104:42: note: expanded
from macro 'rnpvf_rd_reg'
  104 | #define rnpvf_rd_reg(reg) readl((void *)(reg))
        |

Fixes: 6adab536d693 ("drivers: initial support for rnpvf drivers from Mucse Technology")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202407090326.YKEPYjUd-lkp@intel.com/
Signed-off-by: Dong Yibo <dong100@mucse.com>