smb: client: fix smbdirect_recv_io leak in smbd_negotiate() error path
stable inclusion
from stable-v6.6.108
commit e7b7a93879558e77d950f1ff9a6f3daa385b33df
category: bugfix
bugzilla: https://atomgit.com/src-openeuler/kernel/issues/8210
CVE: CVE-2025-39929

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=e7b7a93879558e77d950f1ff9a6f3daa385b33df

--------------------------------

[ Upstream commit daac51c7032036a0ca5f1aa419ad1b0471d1c6e0 ]

During tests of another unrelated patch I was able to trigger this
error: Objects remaining on __kmem_cache_shutdown()

Cc: Steve French <smfrench@gmail.com>
Cc: Tom Talpey <tom@talpey.com>
Cc: Long Li <longli@microsoft.com>
Cc: Namjae Jeon <linkinjeon@kernel.org>
Cc: linux-cifs@vger.kernel.org
Cc: samba-technical@lists.samba.org
Fixes: f198186aa9bb ("CIFS: SMBD: Establish SMB Direct connection")
Signed-off-by: Stefan Metzmacher <metze@samba.org>
Signed-off-by: Steve French <stfrench@microsoft.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Wang Hai <wanghai38@huawei.com>
Signed-off-by: Wang Zhaolong <wangzhaolong@huaweicloud.com>