media: st-delta: avoid excessive stack usage
stable inclusion
from stable-v6.6.112
commit 30a4e81edb15329f795df0bd3d3693dd15ee2dd8
category: bugfix
bugzilla: https://atomgit.com/openeuler/kernel/issues/8637

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=30a4e81edb15329f795df0bd3d3693dd15ee2dd8

--------------------------------

[ Upstream commit 5954ad7d1af92cb6244c5f31216e43af55febbb7 ]

Building with a reduced stack warning limit shows that delta_mjpeg_decode()
copies a giant structure to the stack each time but only uses three of
its members:

drivers/media/platform/st/sti/delta/delta-mjpeg-dec.c: In function 'delta_mjpeg_decode':
drivers/media/platform/st/sti/delta/delta-mjpeg-dec.c:427:1: error: the frame size of 1296 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Open-code the passing of the structure members that are actually used here.

Fixes: 433ff5b4a29b ("[media] st-delta: add mjpeg support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Hans Verkuil <hverkuil+cisco@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 30a4e81edb15329f795df0bd3d3693dd15ee2dd8)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>