xsched: Fix compilation by adding xsched_attr to syscalls.h
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IDCMKR

-----------------------------------------

Add the necessary struct xsched_attr to include/linux/syscalls.h to
make the definition of 'struct xsched_attr' visible during compilation.

This change addresses the following build errors and warnings:
- Warning: 'struct xsched_attr' declared inside parameter list will not be
  visible outside of this definition or declaration.
- Error: conflicting types for 'sys_xsched_setattr' and 'sys_xsched_getattr'

The inclusion of the header ensures consistent type visibility between the
declaration and definition of the system calls involving struct xsched_attr,
preventing type conflicts

Fixes: 7d2bb3c7646c ("xsched: fix compile error when CONFIG_XCU_SCHEDULER is disabled")
Signed-off-by: Juxin Gao <gaojuxin@loongson.cn>