interference: Resolve arm32 build error by restricting IFS to x86/arm64
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ICAOAT

-----------------------------------------

The 64-bit division operations in tdesc_print() and tdesc_init() cause
linkage failures on 32-bit ARM architectures, with errors such as:

arm-linux-gnueabi-ld: kernel/cgroup/ifs.o: in function `tdesc_print':
ifs.c:(.text.unlikely+0xa8): undefined reference to `__aeabi_uldivmod'
arm-linux-gnueabi-ld: ifs.c:(.text.unlikely+0xc4): undefined reference to `__aeabi_uldivmod'
arm-linux-gnueabi-ld: ifs.c:(.text.unlikely+0x130): undefined reference to `__aeabi_uldivmod'
arm-linux-gnueabi-ld: ifs.c:(.text.unlikely+0x14c): undefined reference to `__aeabi_uldivmod'
arm-linux-gnueabi-ld: ifs.c:(.text.unlikely+0x190): undefined reference to `__aeabi_uldivmod'

This occurs because 32-bit ARM lacks native 64-bit division support and
relies on compiler-provided helper functions that may not be available
in all kernel build configurations.

Fix this by restrict its compilation to x86 and ARM64 architectures where
the feature is both usable and safe.

Fixes: bc298fe613e2 ("interference: Add distribution histogram support")
Signed-off-by: Tengda Wu <wutengda2@huawei.com>