x86/idle: Use MONITOR and MWAIT mnemonics in <asm/mwait.h>
mainline inclusion
from mainline-v6.16-rc1
commit fc1cd60042b3df1d162278461c7a87f0362502b8
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/ICUIGI
CVE: NA

Reference: https://github.com/torvalds/linux/commit/fc1cd60042b3df1d162278461c7a87f0362502b8

--------------------------------

commit fc1cd60042b3df1d162278461c7a87f0362502b8 upstream

Current minimum required version of binutils is 2.25,
which supports MONITOR and MWAIT instruction mnemonics.

Replace the byte-wise specification of MONITOR and
MWAIT with these proper mnemonics.

No functional change intended.

Note: LLVM assembler is not able to assemble correct forms of MONITOR
and MWAIT instructions with explicit operands and reports:

  error: invalid operand for instruction
          monitor %rax,%ecx,%edx
                       ^~~~
  # https://lore.kernel.org/oe-kbuild-all/202504030802.2lEVBSpN-lkp@intel.com/

Use instruction mnemonics with implicit operands to
work around this issue.

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Uros Bizjak <ubizjak@gmail.com>
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Acked-by: Borislav Petkov (AMD) <bp@alien8.de>
Link: https://lore.kernel.org/r/20250403125111.429805-1-ubizjak@gmail.com
Signed-off-by: PvsNarasimha <PVS.NarasimhaRao@amd.com>